### ISSUE TITLE
Add Environment example

### ISSUE THREAD

**Issue by DanBrown47** [pygrammers-org/intro.py#17]
Need to provide an example of Environment file in the root.

**Comment by amjedsaleel** [comment]
I think its already in there

**Comment by h4r1337** [comment]
@DanBrown47 It's already in there, in a table format - https://github.com/pygrammers-org/intro.py/tree/main/DjangoRestFrameWork#envexample

**Comment by DanBrown47** [comment]
Ah, Cool
